# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXOS_ROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXOS_BOOT";
      fsType = "vfat";
    };

  fileSystems."/var/lib/chia/farm/F06" =
    { device = "/dev/disk/by-label/F06";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F13" =
    { device = "/dev/disk/by-label/F13";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F14" =
    { device = "/dev/disk/by-label/F14";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/CHIAFARM2" =
    { device = "/dev/disk/by-label/CHIAFARM2";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/CHIAFARM3" =
    { device = "/dev/disk/by-label/CHIAFARM3";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F02" =
    { device = "/dev/disk/by-label/F02";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F03" =
    { device = "/dev/disk/by-label/F03";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F05" =
    { device = "/dev/disk/by-label/F05";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F08" =
    { device = "/dev/disk/by-label/F08";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F11" =
    { device = "/dev/disk/by-label/F11";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  fileSystems."/var/lib/chia/farm/F12" =
    { device = "/dev/disk/by-label/F12";
      fsType = "ext4";
      options = [ "auto" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/NIXOS_SWAP"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
